# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_method', models.CharField(choices=[('QR', 'QR'), ('CODE', 'Verification Code'), ('CREDENTIAL_CODE', 'Credential Code'), ('PUBLIC_SLUG', 'Public Slug')], default='CODE', max_length=24)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requester_user_agent', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=32)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='credentials.credential')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
