# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_code', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('cohort', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang học'), ('GRADUATED', 'Đã tốt nghiệp'), ('SUSPENDED', 'Tạm ngưng'), ('INACTIVE', 'Không hoạt động')], default='ACTIVE', max_length=16)),
                ('credits_completed', models.PositiveIntegerField(default=0)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('finance_hold', models.BooleanField(default=False)),
                ('discipline_hold', models.BooleanField(default=False)),
                ('graduation_eligible', models.BooleanField(default=False)),
                ('graduation_status', models.CharField(blank=True, max_length=120)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=4)),
                ('passed', models.BooleanField(default=False)),
                ('term', models.CharField(max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='students.student')),
            ],
            options={
                'ordering': ['-year', 'term', 'course__code'],
                'unique_together': {('student', 'course', 'term', 'year')},
            },
        ),
    ]
