# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_code', models.CharField(max_length=32, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Đã nộp'), ('UNDER_REVIEW', 'Đang rà soát'), ('ACADEMIC_ELIGIBLE', 'Đủ điều kiện học vụ'), ('FINANCE_CLEARED', 'Đã qua tài chính'), ('DISCIPLINE_CLEARED', 'Đã qua kỷ luật'), ('FINAL_APPROVED', 'Phê duyệt cuối'), ('SIGNED', 'Đã ký'), ('PUBLISHED', 'Đã công bố'), ('REJECTED', 'Từ chối'), ('REVOKED', 'Đã thu hồi'), ('SUPERSEDED', 'Đã thay thế')], default='SUBMITTED', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('evaluation_summary_json', models.JSONField(blank=True, default=dict)),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_requests', to='credentials.credentialtype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_issuance_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_requests', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_requests', to='credentials.credentialtemplate')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[('ACADEMIC', 'Học vụ'), ('EXAMINATION', 'Khảo thí'), ('FINANCE', 'Tài chính'), ('DISCIPLINE', 'Kỷ luật'), ('REGISTRAR', 'Registrar'), ('SIGN_OFF', 'Cho phép ký')], max_length=24)),
                ('assigned_to_role', models.CharField(max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='issuance.issuancerequest')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('request', 'step_type')},
            },
        ),
    ]
