# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('organization_type', models.CharField(choices=[('UNIVERSITY', 'Trường đại học'), ('FACULTY', 'Khoa'), ('DEPARTMENT', 'Bộ môn'), ('TRAINING_OFFICE', 'Phòng đào tạo'), ('EXAMINATION_OFFICE', 'Phòng khảo thí'), ('REGISTRAR', 'Văn phòng registrar'), ('QA', 'Đơn vị QA'), ('PARTNER', 'Đối tác')], default='UNIVERSITY', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_validator', models.BooleanField(default=True)),
                ('can_write_ledger', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('public_visible', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
