# Generated by Django 5.1.6 on 2026-03-21 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_code', models.CharField(max_length=32, unique=True)),
                ('serial_number', models.CharField(max_length=32, unique=True)),
                ('verification_code', models.CharField(max_length=32, unique=True)),
                ('public_slug', models.SlugField(max_length=64, unique=True)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ISSUED', 'Đã cấp'), ('SIGNED', 'Đã ký'), ('PUBLISHED', 'Đã công bố'), ('SUSPENDED', 'Tạm đình chỉ'), ('REVOKED', 'Đã thu hồi'), ('SUPERSEDED', 'Đã thay thế')], default='DRAFT', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('pdf_file', models.FileField(blank=True, upload_to='credentials/pdfs/%Y/%m/%d')),
                ('pdf_hash', models.CharField(blank=True, max_length=128)),
                ('qr_image', models.ImageField(blank=True, upload_to='credentials/qr/%Y/%m/%d')),
                ('signature_value', models.TextField(blank=True)),
                ('signer_name', models.CharField(blank=True, max_length=255)),
                ('signer_title', models.CharField(blank=True, max_length=255)),
                ('ledger_anchor_hash', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('template_config_json', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['credential_type__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_validity_type', models.CharField(blank=True, max_length=120)),
                ('public_fields_json', models.JSONField(blank=True, default=list)),
                ('allow_public_pdf', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CredentialVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(max_length=128)),
                ('pdf_file', models.FileField(blank=True, upload_to='credentials/versions/%Y/%m/%d')),
                ('pdf_hash', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='RevocationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('decision_number', models.CharField(max_length=64)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('public_note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='credentials/revocations/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_algorithm', models.CharField(default='RSA', max_length=32)),
                ('signed_payload_hash', models.CharField(max_length=128)),
                ('signature_value', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(default='RSA', max_length=32)),
                ('public_key_pem', models.TextField()),
                ('private_key_reference', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization__name', 'key_name'],
            },
        ),
    ]
