# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('issuance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='issuance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='issuance.issuancerequest'),
        ),
        migrations.AddField(
            model_name='credential',
            name='issuer_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='credential',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='students.student'),
        ),
        migrations.AddField(
            model_name='credential',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_credentials', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='credential',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='credentials.credentialtemplate'),
        ),
        migrations.AddField(
            model_name='credentialtemplate',
            name='credential_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='credentials.credentialtype'),
        ),
        migrations.AddField(
            model_name='credential',
            name='credential_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='credentials.credentialtype'),
        ),
        migrations.AddField(
            model_name='credentialversion',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='revocationrecord',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocation_records', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='revocationrecord',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_revocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_records', to='credentials.credential'),
        ),
        migrations.AddField(
            model_name='signingkey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='signaturerecord',
            name='signing_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_records', to='credentials.signingkey'),
        ),
        migrations.AlterUniqueTogether(
            name='credentialversion',
            unique_together={('credential', 'version_no')},
        ),
    ]
