# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('ELIGIBILITY', 'Điều kiện cấp'), ('PUBLISHING', 'Điều kiện publish'), ('REVOCATION', 'Điều kiện thu hồi')], default='ELIGIBILITY', max_length=24)),
                ('expression_json', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.BooleanField(default=False)),
                ('detail_json', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_evaluations', to='issuance.issuancerequest')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='policy_engine.policyrule')),
            ],
            options={
                'ordering': ['-executed_at', 'rule__priority'],
            },
        ),
    ]
