# Generated by Django 5.1.6 on 2026-03-21 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('degree_type', models.CharField(max_length=120)),
                ('total_required_credits', models.PositiveIntegerField(default=120)),
                ('min_gpa', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('policy_config_json', models.JSONField(blank=True, default=dict)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_programs', to='organizations.organization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.academicprogram')),
            ],
            options={
                'ordering': ['program__code', 'code'],
            },
        ),
    ]
